name: Deployment pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: |
                echo "Building web application"

            - name: Deploy
              run: |
                echo "Deployed"