name: Load tests

on:
    workflow_run:
        workflows: ["Deployment pipeline"]
        types:
            - completed
        conclusions:
            - success

jobs:
    load-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Load tests
              run: |
                echo "Executing load tests"