name: Load tests

on:
    workflow_run:
        workflows: ["Deployment pipeline"]
        types:
            - completed

jobs:
    load-tests:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Load tests
              run: |
                echo "Executing load tests"